name: Run ESlint on push and pull request

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0

      - uses: actions/setup-node@v2
        with:
          node-version: "18.12.1"

      - name: Install dependencies
        run: npm ci

      - uses: jitterbit/get-changed-files@v1
        id: changed-files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run ESlint
        run: |
          targetFiles=()

          for file in ${{ steps.files.outputs.added_modified }}; do
            if [ "${file#*.}" == "js" ]; then
              targetFiles+=( $file )
            else
              echo "$file file doesnt match the patter"
            fi
          done

          stringFiles="${targetFiles[*]}"
          echo "${stringFiles}"

          npx eslint "$stringFiles"
